"""empty message

Revision ID: 0318172533e6
Revises: 929603768062
Create Date: 2018-08-29 11:41:14.350575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0318172533e6'
down_revision = '929603768062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendace', sa.Column('user_email', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendace', 'user_email')
    # ### end Alembic commands ###
