"""empty message

Revision ID: 0ea394520bfe
Revises: 418d4cbfa9cc
Create Date: 2018-08-30 12:43:07.270809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea394520bfe'
down_revision = '418d4cbfa9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendace', sa.Column('status', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendace', 'status')
    # ### end Alembic commands ###
