"""empty message

Revision ID: 418d4cbfa9cc
Revises: 0318172533e6
Create Date: 2018-08-29 11:42:07.066062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418d4cbfa9cc'
down_revision = '0318172533e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attendace_user_id_fkey', 'attendace', type_='foreignkey')
    op.drop_constraint('attendace_project_id_fkey', 'attendace', type_='foreignkey')
    op.drop_column('attendace', 'user_id')
    op.drop_column('attendace', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendace', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('attendace', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('attendace_project_id_fkey', 'attendace', 'project', ['project_id'], ['id'])
    op.create_foreign_key('attendace_user_id_fkey', 'attendace', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
