"""empty message

Revision ID: 929603768062
Revises: 8cfc39378ed1
Create Date: 2018-08-29 11:20:47.188796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929603768062'
down_revision = '8cfc39378ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendace', sa.Column('project_title', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendace', 'project_title')
    # ### end Alembic commands ###
