"""empty message

Revision ID: a73630225eeb
Revises: 0ea394520bfe
Create Date: 2018-08-30 12:54:55.177683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73630225eeb'
down_revision = '0ea394520bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendace', sa.Column('project_status', sa.String(length=600), nullable=True))
    op.drop_column('attendace', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendace', sa.Column('status', sa.VARCHAR(length=600), autoincrement=False, nullable=True))
    op.drop_column('attendace', 'project_status')
    # ### end Alembic commands ###
